// <auto-generated />
using System;
using EntityFrameworkClassLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkClassLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDoListApp.Todo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = "780423e0-3d45-4efd-bc41-8970892ebeb7",
                            CreatedTime = new DateTime(2023, 2, 7, 12, 13, 21, 51, DateTimeKind.Local).AddTicks(5897),
                            IsCompleted = false,
                            TaskDescription = "Comprare il pane"
                        },
                        new
                        {
                            Id = "00fc28d7-67e5-44a4-91d1-dbc5d2253a04",
                            CreatedTime = new DateTime(2023, 2, 7, 12, 13, 21, 51, DateTimeKind.Local).AddTicks(5904),
                            IsCompleted = false,
                            TaskDescription = "Pagare le bollette"
                        },
                        new
                        {
                            Id = "4ba1dc49-a574-436d-8b5f-8bcf28f1745d",
                            CreatedTime = new DateTime(2023, 2, 7, 12, 13, 21, 51, DateTimeKind.Local).AddTicks(5911),
                            IsCompleted = false,
                            TaskDescription = "Andare in banca"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
