// <auto-generated />
using System;
using EntityFrameworkClassLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkClassLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDoListApp.Todo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = "5dba68c0-1f75-461c-9ba6-01b01d816090",
                            CreatedTime = new DateTime(2023, 2, 10, 15, 39, 36, 507, DateTimeKind.Local).AddTicks(9298),
                            IsCompleted = false,
                            TaskDescription = "Comprare il pane"
                        },
                        new
                        {
                            Id = "42e50217-216e-4e5e-a985-e0ce4006026d",
                            CreatedTime = new DateTime(2023, 2, 10, 15, 39, 36, 507, DateTimeKind.Local).AddTicks(9315),
                            IsCompleted = false,
                            TaskDescription = "Pagare le bollette"
                        },
                        new
                        {
                            Id = "7c3d82f5-95e1-4d5a-b361-871199308f21",
                            CreatedTime = new DateTime(2023, 2, 10, 15, 39, 36, 507, DateTimeKind.Local).AddTicks(9325),
                            IsCompleted = false,
                            TaskDescription = "Andare in banca"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
